### ISSUE TITLE
Рекомендации по написанию SQL скриптов

### ISSUE THREAD

**Issue by sergoio0704** [dmcharlie19/Task3_UniversitySql#1]
https://github.com/dmcharlie19/Task3_UniversitySql/blob/39da09db14781ac916fd3adfa9ac5890a67a8a67/CreateDB.sql#L1

--Рекомендации по написанию SQL скриптов--

1. Зарезервированные слова лучше писать в верхнем регистре
2. При создании таблицы лучше делать проверку на наличие текущей таблицы (IF NOT EXISTS)
3. Называть таблицы, колонки в соответствии с названием сущности
4. Лучше не использовать связующие слова AND, WITH и т д при наименовании таблиц
   Если таблица связывает сущности Student и Group - лучше назвать StudentGroup вместо StudentAndGroup
5. Название таблицы должно быть в единственном числе: Student, Group и т д
6. Для таблицы StudentGroup - лучше создать составной ключ из имеющихся ключей (Student, Group),
   таким образом, мы всегда сможем получить уникальную запись. Т.к 2 одинаковых студента не могут быть в одной группе
7. ON CASCADE DELETE будет автоматически удалять записи в таблице StudentGroup
   если из таблицы [Group]/[Student] удалится какая-то запись
8. Связующие таблицы лучше заполнять программно, если есть такая возможность

Приложил измененный исходный файл скрипта
[university.txt](https://github.com/dmcharlie19/Task3_UniversitySql/files/8234750/university.txt)

**Comment by dmcharlie19** [comment]
ок, исправил
