### ISSUE TITLE
Излишний метод

### ISSUE THREAD

**Issue by sergoio0704** [dmcharlie19/Task3_UniversitySql#2]
https://github.com/dmcharlie19/Task3_UniversitySql/blob/39da09db14781ac916fd3adfa9ac5890a67a8a67/Task3/Program.cs#L44

Думаю, что нет смысла выносить данную логику в отдельный метод и делать его обобщенным (параметризация "T").
В данном случае лучше либо сделать отдельный класс, который будет содержать логику выполнения команд, либо оставить этот функционал в операторе "case"

**Comment by dmcharlie19** [comment]
ок, убрал метод
Изначально так и было, решил как то использовать обобщенный интерфейс
