### ISSUE TITLE
Именования

### ISSUE THREAD

**Issue by sergoio0704** [dmcharlie19/Task3_UniversitySql#3]
https://github.com/dmcharlie19/Task3_UniversitySql/blob/39da09db14781ac916fd3adfa9ac5890a67a8a67/Task3/Program.cs#L46

Лучше явно указывать название сущностей - "units" слишком абстрактное понятие. Можно назвать students, раз метод возвращает коллекцию студентов

**Comment by dmcharlie19** [comment]
ок
