### ISSUE TITLE
Сокращение названий

### ISSUE THREAD

**Issue by sergoio0704** [dmcharlie19/Task3_UniversitySql#5]
https://github.com/dmcharlie19/Task3_UniversitySql/blob/39da09db14781ac916fd3adfa9ac5890a67a8a67/Task3/Program.cs#L91

Не стоит сокращать название переменных, так как при увеличении кода становится тяжело ориентироваться и понимать что такое "fn", "ln' или "s"

**Comment by dmcharlie19** [comment]
ок, переименовал сокращенные переменные
